import { FilesetResolver, HandLandmarker } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest";

const W = 1280, H = 720, canvas = document.querySelector("#game"), ctx = canvas.getContext("2d"), video = document.querySelector("#webcam");
const gate = document.querySelector("#cameraGate"), startButton = document.querySelector("#startCamera");
const COLORS = [[255,85,100],[255,180,53],[104,208,100],[218,82,190],[75,188,232]];
const difficulty = { Easy:{rate:1.02, speed:.86, bomb:.10}, Medium:{rate:.75, speed:1, bomb:.17}, Hard:{rate:.55, speed:1.22, bomb:.24} };
let handLandmarker, pointer = null, previous = null, landmarks = [], lastVideo = -1, state = "menu", selectedDifficulty = "Medium";
let fruits = [], particles = [], score = 0, lives = 10, combo = 0, comboAt = 0, spawnAt = 0, startedAt = 0, last = performance.now(), buttonDwell = {label:"", since:0};
let soundContext, musicTimer, status = "Allow camera access to begin";

const buttons = () => {
  const rows = {
    menu:["PLAY", "HOW TO PLAY", "SETTINGS", "HIGH SCORES"], difficulty:["EASY", "MEDIUM", "HARD", "BACK"],
    instructions:["BACK"], settings:["FULL SCREEN", "BACK"], paused:["RESUME", "RESTART", "MAIN MENU"],
    gameover:["PLAY AGAIN", "MAIN MENU", "HIGH SCORES"], scores:["BACK"]
  }[state] || [];
  const y = state === "instructions" ? 575 : state === "scores" ? 570 : state === "gameover" ? 465 : 310;
  return rows.map((label,i) => ({label, x:W/2-165, y:y+i*72, w:330, h:55}));
};

function audio(name) {
  if (!soundContext) return; const now = soundContext.currentTime;
  const settings = {click:[660,.07,"sine"], slice:[550,.11,"triangle"], bomb:[70,.32,"sawtooth"], lose:[180,.2,"square"], gameover:[125,.55,"sine"]}[name];
  if (!settings) return; const [hz,duration,type] = settings, osc=soundContext.createOscillator(), gain=soundContext.createGain();
  osc.type=type; osc.frequency.setValueAtTime(hz,now); osc.frequency.exponentialRampToValueAtTime(Math.max(35,hz*.55),now+duration);
  gain.gain.setValueAtTime(.12,now); gain.gain.exponentialRampToValueAtTime(.001,now+duration); osc.connect(gain).connect(soundContext.destination); osc.start(now); osc.stop(now+duration);
}
function startMusic() { clearInterval(musicTimer); musicTimer=setInterval(()=>audio("click"), 2200); }
function resetGame(){ fruits=[];particles=[];score=0;lives=10;combo=0;spawnAt=0;startedAt=performance.now(); }
function pointIn(p,b){return p && p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h;}
function choose(label){ audio("click"); if(label==="PLAY"){state="difficulty";} else if(["EASY","MEDIUM","HARD"].includes(label)){selectedDifficulty=label[0]+label.slice(1).toLowerCase();resetGame();state="playing";} else if(label==="HOW TO PLAY")state="instructions"; else if(label==="SETTINGS")state="settings"; else if(label==="HIGH SCORES")state="scores"; else if(label==="FULL SCREEN")canvas.requestFullscreen?.(); else if(label==="RESUME")state="playing"; else if(label==="RESTART"||label==="PLAY AGAIN"){resetGame();state="playing";} else state="menu"; buttonDwell={label:"",since:0}; }
function updateButtons(now){ for(const b of buttons()){if(pointIn(pointer,b)){if(buttonDwell.label!==b.label)buttonDwell={label:b.label,since:now}; if(now-buttonDwell.since>700)choose(b.label); return;} } buttonDwell={label:"",since:0}; }
function makeFruit(){const d=difficulty[selectedDifficulty], bomb=Math.random()<d.bomb; fruits.push({x:80+Math.random()*(W-160),y:H+45,vx:(Math.random()-.5)*350*d.speed,vy:-(650+Math.random()*210)*d.speed,r:bomb?35:29+Math.random()*13,bomb,color:COLORS[(Math.random()*COLORS.length)|0],spin:(Math.random()-.5)*8});}
function burst(x,y,color,count=20){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*260;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,life:.35+Math.random()*.55,size:3+Math.random()*6});}}
function segmentHit(a,b,o){if(!a||!b)return false;const dx=b.x-a.x,dy=b.y-a.y,len=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((o.x-a.x)*dx+(o.y-a.y)*dy)/(len||1)));return Math.hypot(o.x-(a.x+t*dx),o.y-(a.y+t*dy))<o.r+12;}
function lose(x,y,why){lives--;burst(x,y,[255,68,83],38); audio(why==="BOMB"?"bomb":"lose"); if(lives<=0){audio("gameover");saveScore();state="gameover";}}
function saveScore(){const list=JSON.parse(localStorage.getItem("fruitSliceAiScores")||"[]");list.push({score,difficulty:selectedDifficulty});localStorage.setItem("fruitSliceAiScores",JSON.stringify(list.sort((a,b)=>b.score-a.score).slice(0,10)));}
function updateGame(dt,now){const d=difficulty[selectedDifficulty], elapsed=(now-startedAt)/1000;if(now>spawnAt){makeFruit();spawnAt=now+Math.max(260,(d.rate*1000)-(elapsed*2))* (.75+Math.random()*.55);} for(const o of [...fruits]){o.x+=o.vx*dt;o.y+=o.vy*dt;o.vy+=760*dt;if(previous&&pointer&&segmentHit(previous,pointer,o)){fruits.splice(fruits.indexOf(o),1);if(o.bomb)lose(o.x,o.y,"BOMB");else{combo=now<comboAt?combo+1:1;comboAt=now+1300;const gain=10+(combo-1)*5;score+=gain;burst(o.x,o.y,o.color);audio("slice");}}else if(o.y-o.r>H){fruits.splice(fruits.indexOf(o),1);if(!o.bomb)lose(o.x,H-25,"MISSED");}} if(now>comboAt)combo=0;}
function drawBackground(now){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#101a45");g.addColorStop(1,"#46164e");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#fff";for(let i=0;i<35;i++){ctx.globalAlpha=.35;ctx.fillRect((i*173+now*.012*(i%3+1))%W,(i*97)%H,3,3);}ctx.globalAlpha=1;}
function drawFruit(o){ctx.save();ctx.translate(o.x,o.y);ctx.shadowColor="#0008";ctx.shadowBlur=10;ctx.fillStyle=o.bomb?"#31394e":`rgb(${o.color})`;ctx.beginPath();ctx.arc(0,0,o.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(o.bomb){ctx.fillStyle="#8791ab";ctx.beginPath();ctx.arc(-10,-11,8,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#ffcf49";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(7,-o.r+4);ctx.lineTo(17,-o.r-14);ctx.stroke();ctx.fillStyle="#ff6c45";ctx.beginPath();ctx.arc(18,-o.r-15,5,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle="rgba(255,255,255,.45)";ctx.beginPath();ctx.arc(-o.r*.3,-o.r*.3,o.r*.25,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#754723";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,-o.r+4);ctx.lineTo(4,-o.r-10);ctx.stroke();}ctx.restore();}
function label(value,x,y,color="#ffd452",size=28){ctx.fillStyle=color;ctx.font=`800 ${size}px system-ui`;ctx.textAlign="center";ctx.fillText(value,x,y);}
function drawButton(b,now){const active=pointIn(pointer,b), p=active?Math.min(1,(now-buttonDwell.since)/700):0;ctx.fillStyle="#090d29aa";ctx.fillRect(b.x,b.y+5,b.w,b.h);ctx.fillStyle=active?"#3a4c92":"#263561";ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle=active?"#ff6682":"#88a7ea";ctx.lineWidth=2;ctx.strokeRect(b.x,b.y,b.w,b.h);if(active){ctx.fillStyle="#ff5b78";ctx.fillRect(b.x+5,b.y+b.h-7,(b.w-10)*p,3);}label(b.label,b.x+b.w/2,b.y+36,"#fff",24);}
function drawCamera(){const x=20,y=H-182,w=230,h=150;if(video.readyState<2)return;ctx.save();ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(video,0,0,video.videoWidth,video.videoHeight,0,0,w,h);ctx.restore();if(landmarks.length){const p=landmarks.map(v=>({x:x+(1-v.x)*w,y:y+v.y*h}));const links=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[0,9],[9,10],[10,11],[11,12],[0,13],[13,14],[14,15],[15,16],[0,17],[17,18],[18,19],[19,20],[5,9],[9,13],[13,17]];ctx.strokeStyle="#44ffb7";ctx.lineWidth=2;for(const [a,b] of links){ctx.beginPath();ctx.moveTo(p[a].x,p[a].y);ctx.lineTo(p[b].x,p[b].y);ctx.stroke();}p.forEach((v,i)=>{ctx.fillStyle=i===8?"#ff5b78":"#ffe968";ctx.beginPath();ctx.arc(v.x,v.y,i===8?6:3,0,Math.PI*2);ctx.fill();});}ctx.strokeStyle="#b9caef";ctx.strokeRect(x,y,w,h);label("LIVE HAND TRACKING",x+w/2,y+16,"#fff",14);}
function drawScreen(now){label(state==="menu"?"FRUIT SLICE AI":state==="difficulty"?"CHOOSE DIFFICULTY":state==="instructions"?"HOW TO PLAY":state==="settings"?"SETTINGS":state==="paused"?"PAUSED":state==="gameover"?"GAME OVER":"HIGH SCORES",W/2,115,"#ff5b78",62);if(state==="menu")label("Slice fruit with your index finger",W/2,160,"#d8e2ff",23);if(state==="instructions"){["Point your index finger at the camera to move the sword.","Swipe through fruit to slice it. Avoid bombs.","Missing fruit and slicing bombs cost a heart.","Hold your finger over a button to select it."].forEach((t,i)=>label(t,W/2,205+i*40,"#f1f4ff",24));}if(state==="settings")label("Use your browser’s full-screen control for an immersive view.",W/2,210,"#d8e2ff",22);if(state==="gameover")label(`Final score: ${score}`,W/2,190,"#ffd452",32);if(state==="scores"){const list=JSON.parse(localStorage.getItem("fruitSliceAiScores")||"[]");if(!list.length)label("No scores yet — be the first!",W/2,210,"#d8e2ff",24);list.slice(0,6).forEach((s,i)=>label(`${i+1}.    ${s.score}    ${s.difficulty}`,W/2,175+i*42,i?"#f1f4ff":"#ffd452",28));}buttons().forEach(b=>drawButton(b,now));}
function drawPlaying(now){fruits.forEach(drawFruit);particles=particles.filter(p=>(p.life-=.016)>0);particles.forEach(p=>{p.x+=p.vx*.016;p.y+=p.vy*.016;p.vy+=350*.016;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=`rgb(${p.color})`;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;label(`SCORE  ${score}`,28,43,"#fff",26);ctx.textAlign="left";ctx.fillStyle="#ff6682";ctx.font="28px system-ui";ctx.fillText("♥ ".repeat(lives),28,78);label(selectedDifficulty.toUpperCase(),W/2,40,"#ffd452",19);if(combo>1)label(`${combo}x COMBO`,W/2,76,"#ffd452",28);const pause={label:"PAUSE",x:W-145,y:18,w:120,h:43};if(pointIn(pointer,pause)){if(buttonDwell.label!=="PAUSE")buttonDwell={label:"PAUSE",since:now};if(now-buttonDwell.since>700){state="paused";buttonDwell={label:"",since:0};}}else if(buttonDwell.label==="PAUSE")buttonDwell={label:"",since:0};drawButton(pause,now);}
function drawPointer(){if(!pointer)return;ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(pointer.x,pointer.y,17,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#ff5b78";ctx.beginPath();ctx.arc(pointer.x,pointer.y,5,0,Math.PI*2);ctx.fill();}
function gameLoop(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(video.readyState>=2&&handLandmarker&&video.currentTime!==lastVideo){lastVideo=video.currentTime;const r=handLandmarker.detectForVideo(video,now);landmarks=r.landmarks?.[0]||[];previous=pointer;pointer=landmarks.length?{x:(1-landmarks[8].x)*W,y:landmarks[8].y*H}:null;}drawBackground(now);if(state==="playing")updateGame(dt,now);if(state==="playing")drawPlaying(now);else{updateButtons(now);drawScreen(now);}drawCamera();drawPointer();label(status,W/2,H-18,"#c9d7ff",15);requestAnimationFrame(gameLoop);}
async function init(){try{const vision=await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm");handLandmarker=await HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/latest/hand_landmarker.task"},runningMode:"VIDEO",numHands:1,minHandDetectionConfidence:.6,minTrackingConfidence:.55});const stream=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480,facingMode:"user"},audio:false});video.srcObject=stream;await video.play();soundContext=new AudioContext();startMusic();status="Move your index finger to control the sword";gate.classList.add("hidden");requestAnimationFrame(gameLoop);}catch(err){status=`Camera setup failed: ${err.message}`;startButton.textContent="Try camera again";console.error(err);}}
startButton.addEventListener("click",init);
